# Generated by Django 2.2 on 2020-11-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repairdevice',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default='2020-11-18 09:37:53', verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repairdevice',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
