# Generated by Django 2.2 on 2020-11-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='_1c',
            field=models.IntegerField(blank=True, null=True, verbose_name='温控加热启动温度1C(1-30℃)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='_1t',
            field=models.IntegerField(blank=True, null=True, verbose_name='开启冲洗阀时间1T(1-240秒)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='_2c',
            field=models.IntegerField(blank=True, null=True, verbose_name='温控加热停止温度2C(1-30℃)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='_2d',
            field=models.IntegerField(blank=True, null=True, verbose_name='电导率显示方式2D(1TDS 2电导率)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='_2t',
            field=models.IntegerField(blank=True, null=True, verbose_name='开启制水泵时间2T(1-240秒)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='_3d',
            field=models.IntegerField(blank=True, null=True, verbose_name='TDS修正数据3D(0-255)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='_3t',
            field=models.IntegerField(blank=True, null=True, verbose_name='循环冲洗时间3T(1-240秒)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='_4d',
            field=models.IntegerField(blank=True, null=True, verbose_name='洗膜方式4D(1低压 2高压)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='_4t',
            field=models.IntegerField(blank=True, null=True, verbose_name='水满后冲洗时间4T(1-240秒)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='_5t',
            field=models.IntegerField(blank=True, null=True, verbose_name='冲洗时间间隔5T(1-240分)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='_6t',
            field=models.IntegerField(blank=True, null=True, verbose_name='水满制水泵停止时间6T(5-240秒)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='_7t',
            field=models.IntegerField(blank=True, null=True, verbose_name='臭氧杀菌时间7T(5-240秒)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='_8t',
            field=models.IntegerField(blank=True, null=True, verbose_name='臭氧杀菌间隔8T(10-240分)'),
        ),
    ]
