# Generated by Django 2.2 on 2020-11-03 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['online'], name='device_devi_online_53beff_idx'),
        ),
        migrations.AddIndex(
            model_name='device_run_state',
            index=models.Index(fields=['dev_state'], name='device_devi_dev_sta_52a5c4_idx'),
        ),
    ]
