# Generated by Django 2.2 on 2020-11-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20201103_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='MainboardID',
            field=models.CharField(default='zhuban', help_text='主板编号', max_length=50, verbose_name='主板编号'),
            preserve_default=False,
        ),
    ]
