# Generated by Django 2.2 on 2020-11-16 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20201116_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repairdevice',
            old_name='dev_state',
            new_name='deviceNum',
        ),
        migrations.RenameField(
            model_name='repairdevice',
            old_name='repair',
            new_name='repairState',
        ),
    ]
