# Generated by Django 2.2 on 2020-11-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20201118_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repairdevice',
            name='repairID',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='报修编号'),
        ),
    ]
