# Generated by Django 2.2 on 2020-11-06 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_device_mainboardid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_run_state',
            name='dev_state',
            field=models.IntegerField(choices=[(0, '出厂'), (1, '正常制水'), (2, '冲洗'), (3, '水满'), (4, '缺水'), (5, '臭氧'), (6, '清洗前置罐'), (10, '参数设置失败'), (11, '正常制水'), (12, '冲洗'), (13, '水满'), (14, '缺水'), (15, '臭氧'), (16, '清洗前置罐'), (20, '无原水'), (21, '低压'), (30, '无原水'), (31, '低压')], default=0, verbose_name='设备状态'),
        ),
    ]
