# Generated by Django 2.2 on 2020-11-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_auto_20201120_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='_2d',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='电导率显示方式2D(1TDS 2电导率)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='_4d',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='洗膜方式4D(1低压 2高压)'),
        ),
    ]
