# Generated by Django 2.2 on 2020-11-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_auto_20201106_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_run_state',
            name='chongxiFa',
            field=models.BooleanField(default=0, verbose_name='冲洗阀'),
        ),
        migrations.AlterField(
            model_name='device_run_state',
            name='chouYangQi',
            field=models.BooleanField(default=0, verbose_name='臭氧器'),
        ),
        migrations.AlterField(
            model_name='device_run_state',
            name='dev_state',
            field=models.BooleanField(choices=[(0, '出厂'), (1, '正常制水'), (2, '冲洗'), (3, '水满'), (4, '缺水'), (5, '臭氧'), (6, '清洗前置罐'), (10, '参数设置失败'), (11, '正常制水'), (12, '冲洗'), (13, '水满'), (14, '缺水'), (15, '臭氧'), (16, '清洗前置罐'), (20, '无原水'), (21, '低压'), (30, '无原水'), (31, '低压')], default=0, verbose_name='设备状态'),
        ),
        migrations.AlterField(
            model_name='device_run_state',
            name='diyaSwitch',
            field=models.BooleanField(default=0, verbose_name='低压开关'),
        ),
        migrations.AlterField(
            model_name='device_run_state',
            name='gaoYaBeng',
            field=models.BooleanField(default=0, verbose_name='高压泵'),
        ),
        migrations.AlterField(
            model_name='device_run_state',
            name='jinShuiFa',
            field=models.BooleanField(default=0, verbose_name='进水阀'),
        ),
        migrations.AlterField(
            model_name='device_run_state',
            name='remoteSwitch',
            field=models.BooleanField(default=0, verbose_name='远程开关'),
        ),
        migrations.AlterField(
            model_name='device_run_state',
            name='wenKongSwitch',
            field=models.BooleanField(default=0, verbose_name='温控开关'),
        ),
        migrations.AlterField(
            model_name='device_run_state',
            name='yuanShuibeng',
            field=models.BooleanField(default=0, verbose_name='原水泵'),
        ),
    ]
