# Generated by Django 2.2 on 2020-11-08 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_auto_20201106_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device_args_set',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='device_run_state',
            name='device_id',
        ),
        migrations.AddField(
            model_name='device',
            name='deviceArgs',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='device.Device_args_set', verbose_name='设备参数'),
        ),
        migrations.AddField(
            model_name='device',
            name='deviceState',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='device.Device_run_state', verbose_name='设备状态'),
        ),
    ]
