# Generated by Django 2.2 on 2020-11-08 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0008_auto_20201108_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='deviceArgs',
        ),
        migrations.RemoveField(
            model_name='device',
            name='deviceState',
        ),
        migrations.AddField(
            model_name='device_args_set',
            name='device_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_args', to='device.Device', verbose_name='设备ID'),
        ),
        migrations.AddField(
            model_name='device_run_state',
            name='device_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_state', to='device.Device', verbose_name='设备ID'),
        ),
        migrations.AlterField(
            model_name='device_run_state',
            name='chongxiFa',
            field=models.IntegerField(verbose_name='冲洗阀'),
        ),
        migrations.AlterField(
            model_name='device_run_state',
            name='chouYangQi',
            field=models.IntegerField(verbose_name='臭氧器'),
        ),
        migrations.AlterField(
            model_name='device_run_state',
            name='dev_state',
            field=models.CharField(blank=True, choices=[(0, '出厂'), (1, '正常制水'), (2, '冲洗'), (3, '水满'), (4, '缺水'), (5, '臭氧'), (6, '清洗前置罐'), (10, '参数设置失败'), (11, '正常制水'), (12, '冲洗'), (13, '水满'), (14, '缺水'), (15, '臭氧'), (16, '清洗前置罐'), (20, '无原水'), (21, '低压'), (30, '无原水'), (31, '低压')], max_length=2, null=True, verbose_name='设备状态'),
        ),
        migrations.AlterField(
            model_name='device_run_state',
            name='diyaSwitch',
            field=models.IntegerField(verbose_name='低压开关'),
        ),
        migrations.AlterField(
            model_name='device_run_state',
            name='gaoYaBeng',
            field=models.IntegerField(verbose_name='高压泵'),
        ),
        migrations.AlterField(
            model_name='device_run_state',
            name='jinShuiFa',
            field=models.IntegerField(verbose_name='进水阀'),
        ),
        migrations.AlterField(
            model_name='device_run_state',
            name='remoteSwitch',
            field=models.IntegerField(verbose_name='远程开关'),
        ),
        migrations.AlterField(
            model_name='device_run_state',
            name='wenKongSwitch',
            field=models.IntegerField(verbose_name='温控开关'),
        ),
        migrations.AlterField(
            model_name='device_run_state',
            name='yuanShuibeng',
            field=models.IntegerField(verbose_name='原水泵'),
        ),
    ]
