# Generated by Django 2.2 on 2020-11-08 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0010_auto_20201108_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_args_set',
            name='device_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='device_args_set', to='device.Device', verbose_name='设备ID'),
        ),
        migrations.AlterField(
            model_name='device_run_state',
            name='device_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='device_run_state', to='device.Device', verbose_name='设备ID'),
        ),
    ]
