version: "3.8"
   
services:
    db:
        image: mysql
        expose:
        - "3306"
        volumes:
        - ./db:/var/lib/mysql
        environment:
        - MYSQL_DATABASE=achievements
        - MYSQL_ROOT_PASSWORD=root
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
          - .:/code
        ports:
          - "8000:8000"
        depends_on:
          - db