version: "2"

services:
    web:
        build:
          context: .
          dockerfile: ./Dockerfile
        # command: python manage.py runserver 0.0.0.0:8000
        image: circulating_water_sys
        container_name: circulating_water_sys
        working_dir: /myapp
        volumes:
          - .:/myapp
        ports:
          - "8000:8000"
